package com.tools.module.relation

import java.util.regex.Pattern

interface RelationInterface {
    var currentRelative: StringBuilder  // 存储输入数据
    var backRelative: Stack<SqList>
    var sex: String
    var eachRelative: String
    var tempCurrentRelative: SqList //存储用户当前输入且化简后的亲戚关系

    companion object {
        val correspondingAppellation = HashMap<String, String>(1200)
        val eachAppellation = HashMap<String, String>(1200)

        fun init() {
            /*----------------------------最简亲戚关系----------------------------*/
            correspondingAppellation[""] = "自己"
            correspondingAppellation["f"] = "爸爸"
            correspondingAppellation["f,f"] = "爷爷"
            correspondingAppellation["f,f,f"] = "曾祖父"
            correspondingAppellation["f,f,f,f"] = "高祖父"
            correspondingAppellation["f,f,f,f,f"] = "天祖父"
            correspondingAppellation["f,f,f,f,f,f"] = "烈祖父"
            correspondingAppellation["f,f,f,f,f,m"] = "烈祖母"
            correspondingAppellation["f,f,f,f,f,f,f"] = "太祖父"
            correspondingAppellation["f,f,f,f,f,f,m"] = "太祖母"
            correspondingAppellation["f,f,f,f,m"] = "天祖母"
            correspondingAppellation["f,f,f,f,ob"] = "伯高祖父"
            correspondingAppellation["f,f,f,f,ob,w"] = "伯高祖母"
            correspondingAppellation["f,f,f,f,lb"] = "叔高祖父"
            correspondingAppellation["f,f,f,f,lb,w"] = "叔高祖母"
            correspondingAppellation["f,f,f,f,os"] = "姑高祖母"
            correspondingAppellation["f,f,f,f,ls"] = "姑高祖母"
            correspondingAppellation["f,f,f,f,os,h"] = "姑高祖父"
            correspondingAppellation["f,f,f,f,ls,h"] = "姑高祖父"
            correspondingAppellation["f,f,f,m"] = "高祖母"
            correspondingAppellation["f,f,f,m,os"] = "姨高祖母"
            correspondingAppellation["f,f,f,m,ls"] = "姨高祖母"
            correspondingAppellation["f,f,f,m,os,h"] = "姨高祖父"
            correspondingAppellation["f,f,f,m,ls,h"] = "姨高祖父"
            correspondingAppellation["f,f,f,ob"] = "曾伯祖父"
            correspondingAppellation["f,f,f,ob,w"] = "曾伯祖母"
            correspondingAppellation["f,f,f,lb"] = "曾叔祖父"
            correspondingAppellation["f,f,f,lb,w"] = "曾叔祖母"
            correspondingAppellation["f,f,f,ob,s"] = "堂伯祖父/堂叔祖父"
            correspondingAppellation["f,f,f,lb,s"] = "堂伯祖父/堂叔祖父"
            correspondingAppellation["f,f,f,ob,s,w"] = "堂伯祖母/堂叔祖母"
            correspondingAppellation["f,f,f,lb,s,w"] = "堂伯祖母/堂叔祖母"
            correspondingAppellation["f,f,f,ob,s,s"] = "从伯父/从叔父"
            correspondingAppellation["f,f,f,lb,s,s"] = "从伯父/从叔父"
            correspondingAppellation["f,f,f,ob,s,s,w"] = "从伯母/从叔母"
            correspondingAppellation["f,f,f,lb,s,s,w"] = "从伯母/从叔母"
            correspondingAppellation["f,f,f,ob,s,s,s"] = "族兄/族弟"
            correspondingAppellation["f,f,f,lb,s,s,s"] = "族兄/族弟"
            correspondingAppellation["f,f,f,ob,d"] = "堂姑祖母"
            correspondingAppellation["f,f,f,lb,d"] = "堂姑祖母"
            correspondingAppellation["f,f,f,ob,d,h"] = "堂姑祖父"
            correspondingAppellation["f,f,f,lb,d,h"] = "堂姑祖父"
            correspondingAppellation["f,f,f,os"] = "曾祖姑母"
            correspondingAppellation["f,f,f,ls"] = "曾祖姑母"
            correspondingAppellation["f,f,f,os,h"] = "曾祖姑丈"
            correspondingAppellation["f,f,f,ls,h"] = "曾祖姑丈"
            correspondingAppellation["f,f,f,os,s"] = "表伯祖父/表叔祖父"
            correspondingAppellation["f,f,f,ls,s"] = "表伯祖父/表叔祖父"
            correspondingAppellation["f,f,f,os,s,w"] = "表伯祖母/表叔祖母"
            correspondingAppellation["f,f,f,ls,s,w"] = "表伯祖母/表叔祖母"
            correspondingAppellation["f,f,f,os,d"] = "表姑祖母"
            correspondingAppellation["f,f,f,ls,d"] = "表姑祖母"
            correspondingAppellation["f,f,f,os,d,h"] = "表姑祖父"
            correspondingAppellation["f,f,f,ls,d,h"] = "表姑祖父"
            correspondingAppellation["f,f,m"] = "曾祖母"
            correspondingAppellation["f,f,m,f"] = "高外祖父"
            correspondingAppellation["f,f,m,m"] = "高外祖母"
            correspondingAppellation["f,f,m,ob"] = "舅曾祖父"
            correspondingAppellation["f,f,m,lb"] = "舅曾祖父"
            correspondingAppellation["f,f,m,ob,w"] = "舅曾祖母"
            correspondingAppellation["f,f,m,lb,w"] = "舅曾祖母"
            correspondingAppellation["f,f,m,ob,s"] = "表伯祖父/表叔祖父"
            correspondingAppellation["f,f,m,ob,s,w"] = "表伯祖母/表叔祖母"
            correspondingAppellation["f,f,m,lb,s"] = "表伯祖父/表叔祖父"
            correspondingAppellation["f,f,m,lb,s,w"] = "表伯祖母/表叔祖母"
            correspondingAppellation["f,f,m,os,s"] = "表伯祖父/表叔祖父"
            correspondingAppellation["f,f,m,os,s,w"] = "表伯祖母/表叔祖母"
            correspondingAppellation["f,f,m,ls,s"] = "表伯祖父/表叔祖父"
            correspondingAppellation["f,f,m,ls,s,w"] = "表伯祖母/表叔祖母"
            correspondingAppellation["f,f,m,ob,d"] = "表姑祖母"
            correspondingAppellation["f,f,m,lb,d"] = "表姑祖母"
            correspondingAppellation["f,f,m,ob,d,h"] = "表姑祖父"
            correspondingAppellation["f,f,m,lb,d,h"] = "表姑祖父"
            correspondingAppellation["f,f,m,os"] = "姨曾祖母"
            correspondingAppellation["f,f,m,ls"] = "姨曾祖母"
            correspondingAppellation["f,f,m,os,h"] = "姨曾祖父"
            correspondingAppellation["f,f,m,ls,h"] = "姨曾祖父"
            correspondingAppellation["f,f,m,os,d"] = "表姑祖母"
            correspondingAppellation["f,f,m,ls,d"] = "表姑祖母"
            correspondingAppellation["f,f,m,os,d,h"] = "表姑祖父"
            correspondingAppellation["f,f,m,ls,d,h"] = "表姑祖父"
            correspondingAppellation["f,f,ob,s"] = "堂伯/堂叔"
            correspondingAppellation["f,f,ob,s,w"] = "堂伯母/堂叔母"
            correspondingAppellation["f,f,lb,ls"] = "堂伯/堂叔"
            correspondingAppellation["f,f,lb,s,w"] = "堂伯母/堂叔母"
            correspondingAppellation["f,f,ob,s,s"] = "从兄/从弟"
            correspondingAppellation["f,f,ob,s,s,w"] = "从嫂/从弟妹"
            correspondingAppellation["f,f,lb,s,s"] = "从兄/从弟"
            correspondingAppellation["f,f,lb,s,s,w"] = "从嫂/从弟妹"
            correspondingAppellation["f,f,ob"] = "堂祖父"
            correspondingAppellation["f,f,lb"] = "堂祖父"
            correspondingAppellation["f,f,ob,w"] = "堂祖母"
            correspondingAppellation["f,f,lb,w"] = "堂祖母"
            correspondingAppellation["f,f,ob,s,w"] = "堂婶"
            correspondingAppellation["f,f,lb,s,w"] = "堂婶"
            correspondingAppellation["f,f,ob,s,s,s"] = "从侄"
            correspondingAppellation["f,f,lb,s,s,s"] = "从侄"
            correspondingAppellation["f,f,ob,s,s,s,w"] = "从侄媳妇"
            correspondingAppellation["f,f,lb,s,s,s,w"] = "从侄媳妇"
            correspondingAppellation["f,f,ob,s,s,s,s"] = "从侄孙"
            correspondingAppellation["f,f,lb,s,s,s,s"] = "从侄孙"
            correspondingAppellation["f,f,ob,s,s,s,d"] = "从侄孙女"
            correspondingAppellation["f,f,lb,s,s,s,d"] = "从侄孙女"
            correspondingAppellation["f,f,ob,s,s,d"] = "从侄女"
            correspondingAppellation["f,f,lb,s,s,d"] = "从侄女"
            correspondingAppellation["f,f,ob,s,s,d,h"] = "从侄女婿"
            correspondingAppellation["f,f,lb,s,s,d,h"] = "从侄女婿"
            correspondingAppellation["f,f,ob,s,d"] = "从姐/从妹"
            correspondingAppellation["f,f,ob,s,d,h"] = "从姐夫/从妹夫"
            correspondingAppellation["f,f,lb,s,d"] = "从姐/从妹"
            correspondingAppellation["f,f,lb,s,d,h"] = "从姐夫/从妹夫"
            correspondingAppellation["f,f,ob,d"] = "堂姑"
            correspondingAppellation["f,f,lb,d"] = "堂姑"
            correspondingAppellation["f,f,ob,d,h"] = "堂姑丈"
            correspondingAppellation["f,f,lb,d,h"] = "堂姑丈"
            correspondingAppellation["f,f,ob,d,s"] = "堂姑表兄/堂姑表弟"
            correspondingAppellation["f,f,lb,d,s"] = "堂姑表兄/堂姑表弟"
            correspondingAppellation["f,f,ob,d,d"] = "堂姑表姐/堂姑表妹"
            correspondingAppellation["f,f,lb,d,d"] = "堂姑表姐/堂姑表妹"
            correspondingAppellation["f,f,ob"] = "伯祖父"
            correspondingAppellation["f,f,ob,w"] = "伯祖母"
            correspondingAppellation["f,f,lb"] = "叔祖父"
            correspondingAppellation["f,f,lb,w"] = "叔祖母"
            correspondingAppellation["f,f,os"] = "姑奶奶"
            correspondingAppellation["f,f,ls"] = "姑奶奶"
            correspondingAppellation["f,f,os,h"] = "姑爷爷"
            correspondingAppellation["f,f,ls,h"] = "姑爷爷"
            correspondingAppellation["f,f,os,s"] = "姑表伯父/姑表叔父"
            correspondingAppellation["f,f,os,s,w"] = "姑表伯母/姑表叔母"
            correspondingAppellation["f,f,ls,s"] = "姑表伯父/姑表叔父"
            correspondingAppellation["f,f,ls,s,w"] = "姑表伯母/姑表叔母"
            correspondingAppellation["f,f,os,s,s"] = "从表兄弟"
            correspondingAppellation["f,f,ls,s,s"] = "从表兄弟"
            correspondingAppellation["f,f,os,s,d"] = "从表姐妹"
            correspondingAppellation["f,f,ls,s,d"] = "从表姐妹"
            correspondingAppellation["f,f,os,d"] = "姑表姑母"
            correspondingAppellation["f,f,ls,d"] = "姑表姑母"
            correspondingAppellation["f,f,os,d,h"] = "姑表姑父"
            correspondingAppellation["f,f,ls,d,h"] = "姑表姑父"
            correspondingAppellation["f,f,os,d,s"] = "从表兄弟"
            correspondingAppellation["f,f,ls,d,s"] = "从表兄弟"
            correspondingAppellation["f,f,os,d,d"] = "从表姐妹"
            correspondingAppellation["f,f,ls,d,d"] = "从表姐妹"
            correspondingAppellation["f,m"] = "奶奶"
            correspondingAppellation["f,m,f"] = "曾外祖父"
            correspondingAppellation["f,m,f,f"] = "曾外曾祖父"
            correspondingAppellation["f,m,f,m"] = "曾外曾祖母"
            correspondingAppellation["f,m,f,ob,s"] = "堂舅祖父"
            correspondingAppellation["f,m,f,lb,s"] = "堂舅祖父"
            correspondingAppellation["f,m,f,ob,s,w"] = "堂舅祖母"
            correspondingAppellation["f,m,f,lb,s,w"] = "堂舅祖母"
            correspondingAppellation["f,m,f,ob,d"] = "堂姨祖母"
            correspondingAppellation["f,m,f,lb,d"] = "堂姨祖母"
            correspondingAppellation["f,m,f,ob,d,h"] = "堂姨祖父"
            correspondingAppellation["f,m,f,lb,d,h"] = "堂姨祖父"
            correspondingAppellation["f,m,f,ob"] = "伯曾外祖父"
            correspondingAppellation["f,m,f,ob,w"] = "伯曾外祖母"
            correspondingAppellation["f,m,f,lb"] = "叔曾外祖父"
            correspondingAppellation["f,m,f,lb,w"] = "叔曾外祖母"
            correspondingAppellation["f,m,f,os"] = "姑曾外祖母"
            correspondingAppellation["f,m,f,ls"] = "姑曾外祖母"
            correspondingAppellation["f,m,f,os,h"] = "姑曾外祖父"
            correspondingAppellation["f,m,f,ls,h"] = "姑曾外祖父"
            correspondingAppellation["f,m,f,os,s"] = "表舅祖父"
            correspondingAppellation["f,m,f,ls,s"] = "表舅祖父"
            correspondingAppellation["f,m,f,os,s,w"] = "表舅祖母"
            correspondingAppellation["f,m,f,ls,s,w"] = "表舅祖母"
            correspondingAppellation["f,m,m"] = "曾外祖母"
            correspondingAppellation["f,m,m,f"] = "曾外曾外祖父"
            correspondingAppellation["f,m,m,m"] = "曾外曾外祖母"
            correspondingAppellation["f,m,m,ob"] = "舅曾外祖父"
            correspondingAppellation["f,m,m,lb"] = "舅曾外祖父"
            correspondingAppellation["f,m,m,ob,w"] = "舅曾外祖母"
            correspondingAppellation["f,m,m,lb,w"] = "舅曾外祖母"
            correspondingAppellation["f,m,m,ob,s"] = "表舅祖父"
            correspondingAppellation["f,m,m,lb,s"] = "表舅祖父"
            correspondingAppellation["f,m,m,ob,s,w"] = "表舅祖母"
            correspondingAppellation["f,m,m,lb,s,w"] = "表舅祖母"
            correspondingAppellation["f,m,m,ob,d"] = "表姨祖母"
            correspondingAppellation["f,m,m,lb,d"] = "表姨祖母"
            correspondingAppellation["f,m,m,ob,d,h"] = "表姨祖父"
            correspondingAppellation["f,m,m,lb,d,h"] = "表姨祖父"
            correspondingAppellation["f,m,m,os"] = "姨曾外祖母"
            correspondingAppellation["f,m,m,ls"] = "姨曾外祖母"
            correspondingAppellation["f,m,m,os,h"] = "姨曾外祖父"
            correspondingAppellation["f,m,m,ls,h"] = "姨曾外祖父"
            correspondingAppellation["f,m,m,os,d"] = "表姨祖母"
            correspondingAppellation["f,m,m,ls,d"] = "表姨祖母"
            correspondingAppellation["f,m,m,os,d,h"] = "表姨祖父"
            correspondingAppellation["f,m,m,ls,d,h"] = "表姨祖父"
            correspondingAppellation["f,m,m,os,s"] = "表舅祖父"
            correspondingAppellation["f,m,m,ls,s"] = "表舅祖父"
            correspondingAppellation["f,m,m,os,s,w"] = "表舅祖母"
            correspondingAppellation["f,m,m,ls,s,w"] = "表舅祖母"
            correspondingAppellation["f,m,m,os,d"] = "表姨祖母"
            correspondingAppellation["f,m,m,ls,d"] = "表姨祖母"
            correspondingAppellation["f,m,m,os,d,h"] = "表姨祖父"
            correspondingAppellation["f,m,m,ls,d,h"] = "表姨祖父"
            correspondingAppellation["f,m,ob"] = "舅公"
            correspondingAppellation["f,m,ob,w"] = "舅婆"
            correspondingAppellation["f,m,ob,s"] = "舅表伯父/舅表叔父"
            correspondingAppellation["f,m,ob,s,w"] = "舅表伯母/舅表叔母"
            correspondingAppellation["f,m,lb,s"] = "舅表伯父/舅表叔父"
            correspondingAppellation["f,m,lb,s,w"] = "舅表伯母/舅表叔母"
            correspondingAppellation["f,m,ob,s,s"] = "从表兄弟"
            correspondingAppellation["f,m,ob,s,d"] = "从表姐妹"
            correspondingAppellation["f,m,ob,d"] = "舅表姑母"
            correspondingAppellation["f,m,ob,d,h"] = "舅表姑父"
            correspondingAppellation["f,m,ob,d,s"] = "从表兄弟"
            correspondingAppellation["f,m,ob,d,d"] = "从表姐妹"
            correspondingAppellation["f,m,os"] = "姨奶奶"
            correspondingAppellation["f,m,os,h"] = "姨爷爷"
            correspondingAppellation["f,m,os,s"] = "姨表伯父/姨表叔父"
            correspondingAppellation["f,m,os,s,w"] = "姨表伯母/姨表叔母"
            correspondingAppellation["f,m,ls,s"] = "姨表伯父/姨表叔父"
            correspondingAppellation["f,m,ls,,w"] = "姨表伯母/姨表叔母"
            correspondingAppellation["f,m,os,s,s"] = "从表兄弟"
            correspondingAppellation["f,m,os,s,d"] = "从表姐妹"
            correspondingAppellation["f,m,os,d"] = "姨表姑母"
            correspondingAppellation["f,m,os,d,h"] = "姨表姑父"
            correspondingAppellation["f,m,os,d,s"] = "从表兄弟"
            correspondingAppellation["f,m,os,d,d"] = "从表姐妹"
            correspondingAppellation["f,m,lb"] = "舅公"
            correspondingAppellation["f,m,lb,w"] = "舅婆"
            correspondingAppellation["f,m,lb,s,s"] = "从表兄弟"
            correspondingAppellation["f,m,lb,s,d"] = "从表姐妹"
            correspondingAppellation["f,m,lb,d"] = "舅表姑母"
            correspondingAppellation["f,m,lb,d,h"] = "舅表姑父"
            correspondingAppellation["f,m,lb,d,s"] = "从表兄弟"
            correspondingAppellation["f,m,lb,d,d"] = "从表姐妹"
            correspondingAppellation["f,m,ls"] = "姨奶奶"
            correspondingAppellation["f,m,ls,h"] = "姨爷爷"
            correspondingAppellation["f,m,ls,s,s"] = "从表兄弟"
            correspondingAppellation["f,m,ls,s,d"] = "从表姐妹"
            correspondingAppellation["f,m,ls,d"] = "姨表姑母"
            correspondingAppellation["f,m,ls,d,h"] = "姨表姑父"
            correspondingAppellation["f,m,ls,d,s"] = "从表兄弟"
            correspondingAppellation["f,m,ls,d,d"] = "从表姐妹"
            correspondingAppellation["f,ob,w,f"] = "姻伯公"
            correspondingAppellation["f,ob,w,m"] = "姻伯婆"
            correspondingAppellation["f,ob,w,ob"] = "姻世伯"
            correspondingAppellation["f,ob,w,ob,w"] = "姻伯母"
            correspondingAppellation["f,ob,w,os"] = "姻伯母"
            correspondingAppellation["f,ob,w,os,h"] = "姻世伯"
            correspondingAppellation["f,ob,w,lb"] = "姻世伯"
            correspondingAppellation["f,ob,w,lb,w"] = "姻伯母"
            correspondingAppellation["f,ob,w,ls"] = "姻伯母"
            correspondingAppellation["f,ob,w,ls,h"] = "姻世伯"
            correspondingAppellation["f,os,s"] = "姑表哥/姑表弟"
            correspondingAppellation["f,os,s,w"] = "姑表嫂/姑表弟媳"
            correspondingAppellation["f,ls,s"] = "姑表哥/姑表弟"
            correspondingAppellation["f,ls,s,w"] = "姑表嫂/姑表弟媳"
            correspondingAppellation["f,ob,s,s"] = "堂侄"
            correspondingAppellation["f,ob,s,s,w"] = "堂侄媳妇"
            correspondingAppellation["f,ob,s,s,s"] = "堂侄孙"
            correspondingAppellation["f,ob,s,s,s,w"] = "堂侄孙媳妇"
            correspondingAppellation["f,ob,s,s,d"] = "堂侄孙女"
            correspondingAppellation["f,ob,s,s,d,h"] = "堂侄孙女婿"
            correspondingAppellation["f,ob,s,d"] = "堂侄女"
            correspondingAppellation["f,ob,s,d,h"] = "堂侄女婿"
            correspondingAppellation["f,ob,d,s"] = "堂外甥"
            correspondingAppellation["f,ob,d,d"] = "堂外甥女"
            correspondingAppellation["f,lb,w,f"] = "姻伯公"
            correspondingAppellation["f,lb,w,m"] = "姻伯婆"
            correspondingAppellation["f,lb,w,ob"] = "姻世伯"
            correspondingAppellation["f,lb,w,ob,w"] = "姻伯母"
            correspondingAppellation["f,lb,w,os"] = "姻伯母"
            correspondingAppellation["f,lb,w,os,h"] = "姻世伯"
            correspondingAppellation["f,lb,w,lb"] = "姻世伯"
            correspondingAppellation["f,lb,w,lb,w"] = "姻伯母"
            correspondingAppellation["f,lb,w,ls"] = "姻伯母"
            correspondingAppellation["f,lb,w,ls,h"] = "姻世伯"
            correspondingAppellation["f,lb,s,s"] = "堂侄"
            correspondingAppellation["f,lb,s,s,w"] = "堂侄媳妇"
            correspondingAppellation["f,lb,s,s,s"] = "堂侄孙"
            correspondingAppellation["f,lb,s,s,s,w"] = "堂侄孙媳妇"
            correspondingAppellation["f,lb,s,s,d"] = "堂侄孙女"
            correspondingAppellation["f,lb,s,s,d,h"] = "堂侄孙女婿"
            correspondingAppellation["f,lb,s,d"] = "堂侄女"
            correspondingAppellation["f,lb,s,d,h"] = "堂侄女婿"
            correspondingAppellation["f,lb,d"] = "堂姐/堂妹"
            correspondingAppellation["f,lb,s"] = "堂兄/堂弟"
            correspondingAppellation["f,lb,d,s"] = "堂外甥"
            correspondingAppellation["f,lb,d,d"] = "堂外甥女"
            correspondingAppellation["f,ob"] = "伯父"
            correspondingAppellation["f,ob,w"] = "伯母"
            correspondingAppellation["f,ob,d"] = "堂姐/堂妹"
            correspondingAppellation["f,ob,s"] = "堂兄/堂弟"
            correspondingAppellation["f,lb"] = "叔叔"
            correspondingAppellation["f,lb,w"] = "婶婶"
            correspondingAppellation["f,os"] = "姑妈"
            correspondingAppellation["f,os,h"] = "姑丈"
            correspondingAppellation["f,os,h,f"] = "姻伯公"
            correspondingAppellation["f,os,h,m"] = "姻伯婆"
            correspondingAppellation["f,os,h,ob"] = "姻世伯"
            correspondingAppellation["f,os,h,ob,w"] = "姻伯母"
            correspondingAppellation["f,os,h,os"] = "姻伯母"
            correspondingAppellation["f,os,h,os,h"] = "姻世伯"
            correspondingAppellation["f,os,h,lb"] = "姻世伯"
            correspondingAppellation["f,os,h,lb,w"] = "姻伯母"
            correspondingAppellation["f,os,h,ls"] = "姻伯母"
            correspondingAppellation["f,os,h,ls,h"] = "姻世伯"
            correspondingAppellation["f,os,s,s"] = "表侄"
            correspondingAppellation["f,os,s,s,s"] = "表侄孙"
            correspondingAppellation["f,os,s,s,s,w"] = "表侄孙媳妇"
            correspondingAppellation["f,os,s,s,d"] = "表侄孙女"
            correspondingAppellation["f,os,s,s,d,h"] = "表侄孙女婿"
            correspondingAppellation["f,os,s,d"] = "表侄女"
            correspondingAppellation["f,os,s,d,s"] = "外表侄孙"
            correspondingAppellation["f,os,s,d,s,w"] = "外表侄孙媳妇"
            correspondingAppellation["f,os,s,d,d"] = "外表侄孙女"
            correspondingAppellation["f,os,s,d,d,h"] = "外表侄孙女婿"
            correspondingAppellation["f,os,d"] = "姑表姐/姑表妹"
            correspondingAppellation["f,os,d,h"] = "姑表姐夫/姑表妹夫"
            correspondingAppellation["f,ls,d"] = "姑表姐/姑表妹"
            correspondingAppellation["f,ls,d,h"] = "姑表姐夫/姑表妹夫"
            correspondingAppellation["f,os,d,s"] = "表外甥"
            correspondingAppellation["f,os,d,d"] = "表外甥女"
            correspondingAppellation["f,ls"] = "姑妈"
            correspondingAppellation["f,ls,h"] = "姑丈"
            correspondingAppellation["f,ls,h,f"] = "姻伯公"
            correspondingAppellation["f,ls,h,m"] = "姻伯婆"
            correspondingAppellation["f,ls,h,ob"] = "姻世伯"
            correspondingAppellation["f,ls,h,ob,w"] = "姻伯母"
            correspondingAppellation["f,ls,h,os"] = "姻伯母"
            correspondingAppellation["f,ls,h,os,h"] = "姻世伯"
            correspondingAppellation["f,ls,h,lb"] = "姻世伯"
            correspondingAppellation["f,ls,h,lb,w"] = "姻伯母"
            correspondingAppellation["f,ls,h,ls"] = "姻伯母"
            correspondingAppellation["f,ls,h,ls,h"] = "姻世伯"
            correspondingAppellation["f,ls,s,s"] = "表侄"
            correspondingAppellation["f,ls,s,s,s"] = "表侄孙"
            correspondingAppellation["f,ls,s,s,s,w"] = "表侄孙媳妇"
            correspondingAppellation["f,ls,s,s,d"] = "表侄孙女"
            correspondingAppellation["f,ls,s,s,d,h"] = "表侄孙女婿"
            correspondingAppellation["f,ls,s,d"] = "表侄女"
            correspondingAppellation["f,ls,s,d,s"] = "外表侄孙"
            correspondingAppellation["f,ls,s,d,s,w"] = "外表侄孙媳妇"
            correspondingAppellation["f,ls,s,d,d"] = "外表侄孙女"
            correspondingAppellation["f,ls,s,d,d,h"] = "外表侄孙女婿"
            correspondingAppellation["f,ls,d,s"] = "表外甥"
            correspondingAppellation["f,ls,d,d"] = "表外甥女"
            correspondingAppellation["f,os"] = "姑妈"
            correspondingAppellation["f,ls"] = "姑妈"
            correspondingAppellation["m"] = "妈妈"
            correspondingAppellation["m,f"] = "外公"
            correspondingAppellation["m,f,f"] = "外曾祖父"
            correspondingAppellation["m,f,f,f"] = "外高祖父"
            correspondingAppellation["m,f,f,m"] = "外高祖母"
            correspondingAppellation["m,f,f,ob,s"] = "堂伯外祖父/堂叔外祖父"
            correspondingAppellation["m,f,f,ob,s,w"] = "堂伯外祖母/堂叔外祖母"
            correspondingAppellation["m,f,f,lb,s"] = "堂伯外祖父/堂叔外祖父"
            correspondingAppellation["m,f,f,lb,s,w"] = "堂伯外祖母/堂叔外祖母"
            correspondingAppellation["m,f,f,ob,d"] = "堂姑外祖母"
            correspondingAppellation["m,f,f,ob,d,h"] = "堂姑外祖父"
            correspondingAppellation["m,f,f,lb,d"] = "堂姑外祖母"
            correspondingAppellation["m,f,f,lb,d,h"] = "堂姑外祖父"
            correspondingAppellation["m,f,f,ob"] = "伯外曾祖父"
            correspondingAppellation["m,f,f,ob,w"] = "伯外曾祖母"
            correspondingAppellation["m,f,f,lb"] = "叔外曾祖父"
            correspondingAppellation["m,f,f,lb,w"] = "叔外曾祖母"
            correspondingAppellation["m,f,f,os"] = "姑外曾祖母"
            correspondingAppellation["m,f,f,os,h"] = "姑外曾祖父"
            correspondingAppellation["m,f,f,os,s"] = "表伯外祖父/表叔外祖父"
            correspondingAppellation["m,f,f,os,s,w"] = "表伯外祖母/表叔外祖母"
            correspondingAppellation["m,f,f,ls,s"] = "表伯外祖父/表叔外祖父"
            correspondingAppellation["m,f,f,ls,s,w"] = "表伯外祖母/表叔外祖母"
            correspondingAppellation["m,f,f,os,d"] = "表姑外祖母"
            correspondingAppellation["m,f,f,os,d,h"] = "表姑外祖父"
            correspondingAppellation["m,f,f,ls"] = "姑外曾祖母"
            correspondingAppellation["m,f,f,ls,h"] = "姑外曾祖父"
            correspondingAppellation["m,f,f,ls,d"] = "表姑外祖母"
            correspondingAppellation["m,f,f,ls,d,h"] = "表姑外祖父"
            correspondingAppellation["m,f,m"] = "外曾祖母"
            correspondingAppellation["m,f,m,f"] = "外高外祖父"
            correspondingAppellation["m,f,m,m"] = "外高外祖母"
            correspondingAppellation["m,f,m,ob"] = "舅外曾祖父"
            correspondingAppellation["m,f,m,ob,w"] = "舅外曾祖母"
            correspondingAppellation["m,f,m,ob,d"] = "表姑外祖母"
            correspondingAppellation["m,f,m,ob,d,h"] = "表姑外祖父"
            correspondingAppellation["m,f,m,os"] = "姨外曾祖母"
            correspondingAppellation["m,f,m,os,h"] = "姨外曾祖父"
            correspondingAppellation["m,f,m,os,d"] = "表姑外祖母"
            correspondingAppellation["m,f,m,os,d,h"] = "表姑外祖父"
            correspondingAppellation["m,f,ob"] = "大姥爷/小姥爷"
            correspondingAppellation["m,f,ob,s"] = "堂舅"
            correspondingAppellation["m,f,ob,s,w"] = "堂舅妈"
            correspondingAppellation["m,f,ob,s,s"] = "堂舅表兄/堂舅表弟"
            correspondingAppellation["m,f,lb,s,s"] = "堂舅表兄/堂舅表弟"
            correspondingAppellation["m,f,ob,s,d"] = "堂舅表姐/堂舅表妹"
            correspondingAppellation["m,f,lb,s,d"] = "堂舅表姐/堂舅表妹"
            correspondingAppellation["m,f,ob,d"] = "堂姨"
            correspondingAppellation["m,f,ob,d,h"] = "堂姨丈"
            correspondingAppellation["m,f,ob,d,s"] = "堂姨表兄/堂姨表弟"
            correspondingAppellation["m,f,ob,d,d"] = "堂姨表姐/堂姨表妹"
            correspondingAppellation["m,f,lb,d,s"] = "堂姨表兄/堂姨表弟"
            correspondingAppellation["m,f,lb,d,d"] = "堂姨表姐/堂姨表妹"
            correspondingAppellation["m,f,m,lb"] = "舅外曾祖父"
            correspondingAppellation["m,f,m,lb,w"] = "舅外曾祖母"
            correspondingAppellation["m,f,m,lb,d"] = "表姑外祖母"
            correspondingAppellation["m,f,m,lb,d,h"] = "表姑外祖父"
            correspondingAppellation["m,f,m,ls"] = "姨外曾祖母"
            correspondingAppellation["m,f,m,ls,h"] = "姨外曾祖父"
            correspondingAppellation["m,f,m,ls,d"] = "表姑外祖母"
            correspondingAppellation["m,f,m,ls,d,h"] = "表姑外祖父"
            correspondingAppellation["m,f,lb"] = "大姥爷/小姥爷"
            correspondingAppellation["m,f,lb,s"] = "堂舅"
            correspondingAppellation["m,f,lb,s,w"] = "堂舅妈"
            correspondingAppellation["m,f,lb,d"] = "堂姨"
            correspondingAppellation["m,f,lb,d,h"] = "堂姨丈"
            correspondingAppellation["m,f,ob"] = "伯外祖父"
            correspondingAppellation["m,f,ob,w"] = "伯外祖母"
            correspondingAppellation["m,f,lb"] = "叔外祖父"
            correspondingAppellation["m,f,lb,w"] = "叔外祖母"
            correspondingAppellation["m,f,os"] = "姑姥姥"
            correspondingAppellation["m,f,os,h"] = "姑姥爷"
            correspondingAppellation["m,f,os,s"] = "姑表舅父"
            correspondingAppellation["m,f,os,s,w"] = "姑表舅母"
            correspondingAppellation["m,f,os,s,s"] = "从表兄弟"
            correspondingAppellation["m,f,os,s,d"] = "从表姐妹"
            correspondingAppellation["m,f,os,d"] = "姑表姨母"
            correspondingAppellation["m,f,os,d,h"] = "姑表姨父"
            correspondingAppellation["m,f,os,d,s"] = "从表兄弟"
            correspondingAppellation["m,f,os,d,d"] = "从表姐妹"
            correspondingAppellation["m,f,ls"] = "姑姥姥"
            correspondingAppellation["m,f,ls,h"] = "姑姥爷"
            correspondingAppellation["m,f,ls,s"] = "姑表舅父"
            correspondingAppellation["m,f,ls,s,w"] = "姑表舅母"
            correspondingAppellation["m,f,ls,s,s"] = "从表兄弟"
            correspondingAppellation["m,f,ls,s,d"] = "从表姐妹"
            correspondingAppellation["m,f,ls,d"] = "姑表姨母"
            correspondingAppellation["m,f,ls,d,h"] = "姑表姨父"
            correspondingAppellation["m,f,ls,d,s"] = "从表兄弟"
            correspondingAppellation["m,f,ls,d,d"] = "从表姐妹"
            correspondingAppellation["m,m"] = "外婆"
            correspondingAppellation["m,m,f"] = "外曾外祖父"
            correspondingAppellation["m,m,f,f"] = "外曾外曾祖父"
            correspondingAppellation["m,m,f,m"] = "外曾外曾祖母"
            correspondingAppellation["m,m,f,ob,s"] = "堂舅外祖父"
            correspondingAppellation["m,m,f,ob,s,w"] = "堂舅外祖母"
            correspondingAppellation["m,m,f,ob,d"] = "堂姨外祖母"
            correspondingAppellation["m,m,f,ob,d,h"] = "堂姨外祖父"
            correspondingAppellation["m,m,f,lb,s"] = "堂舅外祖父"
            correspondingAppellation["m,m,f,lb,s,w"] = "堂舅外祖母"
            correspondingAppellation["m,m,f,lb,d"] = "堂姨外祖母"
            correspondingAppellation["m,m,f,lb,d,h"] = "堂姨外祖父"
            correspondingAppellation["m,m,f,ob"] = "伯外曾外祖父"
            correspondingAppellation["m,m,f,ob,w"] = "伯外曾外祖母"
            correspondingAppellation["m,m,f,lb"] = "叔外曾外祖父"
            correspondingAppellation["m,m,f,lb,w"] = "叔外曾外祖母"
            correspondingAppellation["m,m,f,os"] = "姑外曾外祖母"
            correspondingAppellation["m,m,f,os,h"] = "姑外曾外祖父"
            correspondingAppellation["m,m,f,os,s"] = "表舅外祖父"
            correspondingAppellation["m,m,f,os,s,w"] = "表舅外祖母"
            correspondingAppellation["m,m,f,os,d"] = "表姨外祖母"
            correspondingAppellation["m,m,f,os,d,h"] = "表姨外祖父"
            correspondingAppellation["m,m,f,ls"] = "姑外曾外祖母"
            correspondingAppellation["m,m,f,ls,h"] = "姑外曾外祖父"
            correspondingAppellation["m,m,f,ls,s"] = "表舅外祖父"
            correspondingAppellation["m,m,f,ls,s,w"] = "表舅外祖母"
            correspondingAppellation["m,m,f,ls,d"] = "表姨外祖母"
            correspondingAppellation["m,m,f,ls,d,h"] = "表姨外祖父"
            correspondingAppellation["m,m,m"] = "外曾外祖母"
            correspondingAppellation["m,m,m,f"] = "外曾外曾外祖父"
            correspondingAppellation["m,m,m,m"] = "外曾外曾外祖母"
            correspondingAppellation["m,m,m,ob"] = "舅外曾外祖父"
            correspondingAppellation["m,m,m,ob,w"] = "舅外曾外祖母"
            correspondingAppellation["m,m,m,ob,s"] = "表舅外祖父"
            correspondingAppellation["m,m,m,ob,s,w"] = "表舅外祖母"
            correspondingAppellation["m,m,m,ob,d"] = "表姨外祖母"
            correspondingAppellation["m,m,m,ob,d,h"] = "表姨外祖父"
            correspondingAppellation["m,m,m,os"] = "姨外曾外祖母"
            correspondingAppellation["m,m,m,os,h"] = "姨外曾外祖父"
            correspondingAppellation["m,m,m,os,s"] = "表舅外祖父"
            correspondingAppellation["m,m,m,os,s,w"] = "表舅外祖母"
            correspondingAppellation["m,m,m,os,d"] = "表姨外祖母"
            correspondingAppellation["m,m,m,os,d,h"] = "表姨外祖父"
            correspondingAppellation["m,m,ob"] = "外舅公"
            correspondingAppellation["m,m,ob,w"] = "外舅婆"
            correspondingAppellation["m,m,ob,s"] = "舅表舅父"
            correspondingAppellation["m,m,ob,s,w"] = "舅表舅母"
            correspondingAppellation["m,m,ob,s,s"] = "从表兄弟"
            correspondingAppellation["m,m,ob,s,d"] = "从表姐妹"
            correspondingAppellation["m,m,ob,d"] = "舅表姨母"
            correspondingAppellation["m,m,ob,d,h"] = "舅表姨父"
            correspondingAppellation["m,m,ob,d,s"] = "从表兄弟"
            correspondingAppellation["m,m,ob,d,d"] = "从表姐妹"
            correspondingAppellation["m,m,os"] = "姨姥姥"
            correspondingAppellation["m,m,os,h"] = "姨姥爷"
            correspondingAppellation["m,m,os,s"] = "姨表舅父"
            correspondingAppellation["m,m,os,s,w"] = "姨表舅母"
            correspondingAppellation["m,m,os,s,s"] = "从表兄弟"
            correspondingAppellation["m,m,os,s,d"] = "从表姐妹"
            correspondingAppellation["m,m,os,d"] = "姨表姨母"
            correspondingAppellation["m,m,os,d,h"] = "姨表姨父"
            correspondingAppellation["m,m,os,d,s"] = "从表兄弟"
            correspondingAppellation["m,m,os,d,d"] = "从表姐妹"
            correspondingAppellation["m,ob"] = "舅舅"
            correspondingAppellation["m,ob,w"] = "舅妈"
            correspondingAppellation["m,ob,w,f"] = "姻伯公"
            correspondingAppellation["m,ob,w,m"] = "姻伯婆"
            correspondingAppellation["m,ob,w,ob"] = "姻世伯"
            correspondingAppellation["m,ob,w,ob,w"] = "姻伯母"
            correspondingAppellation["m,ob,w,os"] = "姻伯母"
            correspondingAppellation["m,ob,w,os,h"] = "姻世伯"
            correspondingAppellation["m,ob,w,lb"] = "姻世伯"
            correspondingAppellation["m,ob,w,lb,w"] = "姻伯母"
            correspondingAppellation["m,ob,w,ls"] = "姻伯母"
            correspondingAppellation["m,ob,w,ls,h"] = "姻世伯"
            correspondingAppellation["m,ob,s"] = "舅表哥/舅表弟"
            correspondingAppellation["m,ob,s,w"] = "舅表嫂/舅表弟媳"
            correspondingAppellation["m,lb,s"] = "舅表哥/舅表弟"
            correspondingAppellation["m,lb,s,w"] = "舅表嫂/舅表弟媳"
            correspondingAppellation["m,ob,s,s"] = "表侄"
            correspondingAppellation["m,ob,s,s,s"] = "表侄孙"
            correspondingAppellation["m,ob,s,s,s,w"] = "表侄孙媳妇"
            correspondingAppellation["m,ob,s,s,d"] = "表侄孙女"
            correspondingAppellation["m,ob,s,s,d,h"] = "表侄孙女婿"
            correspondingAppellation["m,ob,s,d"] = "表侄女"
            correspondingAppellation["m,ob,s,d,s"] = "外表侄孙"
            correspondingAppellation["m,ob,s,d,s,w"] = "外表侄孙媳妇"
            correspondingAppellation["m,ob,s,d,d"] = "外表侄孙女"
            correspondingAppellation["m,ob,s,d,d,h"] = "外表侄孙女婿"
            correspondingAppellation["m,ob,d,s"] = "表外甥"
            correspondingAppellation["m,ob,d,d"] = "表外甥女"
            correspondingAppellation["m,m,m,lb"] = "舅外曾外祖父"
            correspondingAppellation["m,m,m,lb,w"] = "舅外曾外祖母"
            correspondingAppellation["m,m,m,lb,s"] = "表舅外祖父"
            correspondingAppellation["m,m,m,lb,s,w"] = "表舅外祖母"
            correspondingAppellation["m,m,m,lb,d"] = "表姨外祖母"
            correspondingAppellation["m,m,m,lb,d,h"] = "表姨外祖父"
            correspondingAppellation["m,m,m,ls"] = "姨外曾外祖母"
            correspondingAppellation["m,m,m,ls,h"] = "姨外曾外祖父"
            correspondingAppellation["m,m,m,ls,s"] = "表舅外祖父"
            correspondingAppellation["m,m,m,ls,s,w"] = "表舅外祖母"
            correspondingAppellation["m,m,m,ls,d"] = "表姨外祖母"
            correspondingAppellation["m,m,m,ls,d,h"] = "表姨外祖父"
            correspondingAppellation["m,m,lb"] = "外舅公"
            correspondingAppellation["m,m,lb,w"] = "外舅婆"
            correspondingAppellation["m,m,lb,s"] = "舅表舅父"
            correspondingAppellation["m,m,lb,s,w"] = "舅表舅母"
            correspondingAppellation["m,m,lb,s,s"] = "从表兄弟"
            correspondingAppellation["m,m,lb,s,d"] = "从表姐妹"
            correspondingAppellation["m,m,lb,d"] = "舅表姨母"
            correspondingAppellation["m,m,lb,d,h"] = "舅表姨父"
            correspondingAppellation["m,m,lb,d,s"] = "从表兄弟"
            correspondingAppellation["m,m,lb,d,d"] = "从表姐妹"
            correspondingAppellation["m,m,ls"] = "姨姥姥"
            correspondingAppellation["m,m,ls,h"] = "姨姥爷"
            correspondingAppellation["m,m,ls,s"] = "姨表舅父"
            correspondingAppellation["m,m,ls,s,w"] = "姨表舅母"
            correspondingAppellation["m,m,ls,s,s"] = "从表兄弟"
            correspondingAppellation["m,m,ls,s,d"] = "从表姐妹"
            correspondingAppellation["m,m,ls,d"] = "姨表姨母"
            correspondingAppellation["m,m,ls,d,h"] = "姨表姨父"
            correspondingAppellation["m,m,ls,d,s"] = "从表兄弟"
            correspondingAppellation["m,m,ls,d,d"] = "从表姐妹"
            correspondingAppellation["m,lb"] = "舅舅"
            correspondingAppellation["m,lb,w"] = "舅妈"
            correspondingAppellation["m,lb,w,f"] = "姻伯公"
            correspondingAppellation["m,lb,w,m"] = "姻伯婆"
            correspondingAppellation["m,lb,w,ob"] = "姻世伯"
            correspondingAppellation["m,lb,w,ob,w"] = "姻伯母"
            correspondingAppellation["m,lb,w,os"] = "姻伯母"
            correspondingAppellation["m,lb,w,os,h"] = "姻世伯"
            correspondingAppellation["m,lb,w,lb"] = "姻世伯"
            correspondingAppellation["m,lb,w,lb,w"] = "姻伯母"
            correspondingAppellation["m,lb,w,ls"] = "姻伯母"
            correspondingAppellation["m,lb,w,ls,h"] = "姻世伯"
            correspondingAppellation["m,lb,s,s"] = "表侄"
            correspondingAppellation["m,lb,s,s,s"] = "表侄孙"
            correspondingAppellation["m,lb,s,s,s,w"] = "表侄孙媳妇"
            correspondingAppellation["m,lb,s,s,d"] = "表侄孙女"
            correspondingAppellation["m,lb,s,s,d,h"] = "表侄孙女婿"
            correspondingAppellation["m,lb,s,d"] = "表侄女"
            correspondingAppellation["m,lb,s,d,s"] = "外表侄孙"
            correspondingAppellation["m,lb,s,d,s,w"] = "外表侄孙媳妇"
            correspondingAppellation["m,lb,s,d,d"] = "外表侄孙女"
            correspondingAppellation["m,lb,s,d,d,h"] = "外表侄孙女婿"
            correspondingAppellation["m,ob,d"] = "舅表姐/舅表妹"
            correspondingAppellation["m,ob,d,h"] = "舅表姐夫/舅表妹夫"
            correspondingAppellation["m,lb,d"] = "舅表姐/舅表妹"
            correspondingAppellation["m,lb,d,h"] = "舅表姐夫/舅表妹夫"
            correspondingAppellation["m,lb,d,s"] = "表外甥"
            correspondingAppellation["m,lb,d,d"] = "表外甥女"
            correspondingAppellation["m,ob"] = "大舅"
            correspondingAppellation["m,ob,w"] = "大舅妈"
            correspondingAppellation["m,lb"] = "小舅"
            correspondingAppellation["m,lb,w"] = "小舅妈"
            correspondingAppellation["m,os"] = "姨妈"
            correspondingAppellation["m,os,h"] = "姨丈"
            correspondingAppellation["m,os,h,f"] = "姻伯公"
            correspondingAppellation["m,os,h,m"] = "姻伯婆"
            correspondingAppellation["m,os,h,ob"] = "姻世伯"
            correspondingAppellation["m,os,h,ob,w"] = "姻伯母"
            correspondingAppellation["m,os,h,os"] = "姻伯母"
            correspondingAppellation["m,os,h,os,h"] = "姻世伯"
            correspondingAppellation["m,os,h,lb"] = "姻世伯"
            correspondingAppellation["m,os,h,lb,w"] = "姻伯母"
            correspondingAppellation["m,os,h,ls"] = "姻伯母"
            correspondingAppellation["m,os,h,ls,h"] = "姻世伯"
            correspondingAppellation["m,os,s"] = "姨表哥/姨表弟"
            correspondingAppellation["m,os,s,w"] = "姨表嫂/姨表弟媳"
            correspondingAppellation["m,ls,s"] = "姨表哥/姨表弟"
            correspondingAppellation["m,ls,s,w"] = "姨表嫂/姨表弟媳"
            correspondingAppellation["m,os,s,s"] = "表侄"
            correspondingAppellation["m,os,s,s,s"] = "表侄孙"
            correspondingAppellation["m,os,s,s,s,w"] = "表侄孙媳妇"
            correspondingAppellation["m,os,s,s,d"] = "表侄孙女"
            correspondingAppellation["m,os,s,s,d,h"] = "表侄孙女婿"
            correspondingAppellation["m,os,s,d"] = "表侄女"
            correspondingAppellation["m,os,s,d,s"] = "外表侄孙"
            correspondingAppellation["m,os,s,d,s,w"] = "外表侄孙媳妇"
            correspondingAppellation["m,os,s,d,d"] = "外表侄孙女"
            correspondingAppellation["m,os,s,d,d,h"] = "外表侄孙女婿"
            correspondingAppellation["m,os,d,s"] = "表外甥"
            correspondingAppellation["m,os,d,d"] = "表外甥女"
            correspondingAppellation["m,ls"] = "姨妈"
            correspondingAppellation["m,ls,h"] = "姨丈"
            correspondingAppellation["m,ls,h,f"] = "姻伯公"
            correspondingAppellation["m,ls,h,m"] = "姻伯婆"
            correspondingAppellation["m,ls,h,ob"] = "姻世伯"
            correspondingAppellation["m,ls,h,ob,w"] = "姻伯母"
            correspondingAppellation["m,ls,h,os"] = "姻伯母"
            correspondingAppellation["m,ls,h,os,h"] = "姻世伯"
            correspondingAppellation["m,ls,h,lb"] = "姻世伯"
            correspondingAppellation["m,ls,h,lb,w"] = "姻伯母"
            correspondingAppellation["m,ls,h,ls"] = "姻伯母"
            correspondingAppellation["m,ls,h,ls,h"] = "姻世伯"
            correspondingAppellation["m,ls,s,s"] = "表侄"
            correspondingAppellation["m,ls,s,s,s"] = "表侄孙"
            correspondingAppellation["m,ls,s,s,s,w"] = "表侄孙媳妇"
            correspondingAppellation["m,ls,s,s,d"] = "表侄孙女"
            correspondingAppellation["m,ls,s,s,d,h"] = "表侄孙女婿"
            correspondingAppellation["m,ls,s,d"] = "表侄女"
            correspondingAppellation["m,ls,s,d,s"] = "外表侄孙"
            correspondingAppellation["m,ls,s,d,s,w"] = "外表侄孙媳妇"
            correspondingAppellation["m,ls,s,d,d"] = "外表侄孙女"
            correspondingAppellation["m,ls,s,d,d,h"] = "外表侄孙女婿"
            correspondingAppellation["m,os,d"] = "姨表姐/姨表妹"
            correspondingAppellation["m,os,d,h"] = "姨表姐夫/姨表妹夫"
            correspondingAppellation["m,ls,d"] = "姨表姐/姨表妹"
            correspondingAppellation["m,ls,d,h"] = "姨表姐夫/姨表妹夫"
            correspondingAppellation["m,ls,d,s"] = "表外甥"
            correspondingAppellation["m,ls,d,d"] = "表外甥女"
            correspondingAppellation["m,os"] = "大姨"
            correspondingAppellation["m,os,h"] = "大姨父"
            correspondingAppellation["m,ls"] = "小姨"
            correspondingAppellation["m,ls,h"] = "小姨父"
            correspondingAppellation["h"] = "老公"
            correspondingAppellation["h,f"] = "公公"
            correspondingAppellation["h,f,f"] = "祖翁"
            correspondingAppellation["h,f,f,ob"] = "伯祖翁"
            correspondingAppellation["h,f,f,ob,w"] = "伯祖婆"
            correspondingAppellation["h,f,f,lb"] = "叔祖翁"
            correspondingAppellation["h,f,f,lb,w"] = "叔祖婆"
            correspondingAppellation["h,f,f,f"] = "太公翁"
            correspondingAppellation["h,f,f,f,ob"] = "太伯翁"
            correspondingAppellation["h,f,f,f,ob,w"] = "太姆婆"
            correspondingAppellation["h,f,f,f,lb"] = "太叔翁"
            correspondingAppellation["h,f,f,f,lb,w"] = "太婶婆"
            correspondingAppellation["h,f,f,m"] = "太奶亲"
            correspondingAppellation["h,f,m"] = "祖婆"
            correspondingAppellation["h,f,ob"] = "伯翁"
            correspondingAppellation["h,f,ob,w"] = "伯婆"
            correspondingAppellation["h,f,lb"] = "叔公"
            correspondingAppellation["h,f,lb,w"] = "叔婆"
            correspondingAppellation["h,f,ob,s"] = "堂大伯/堂叔仔"
            correspondingAppellation["h,f,ob,s,w"] = "堂嫂/堂小弟"
            correspondingAppellation["h,f,lb,s"] = "堂大伯/堂叔仔"
            correspondingAppellation["h,f,lb,s,w"] = "堂嫂/堂小弟"
            correspondingAppellation["h,f,ob,s,s"] = "堂夫侄男"
            correspondingAppellation["h,f,ob,s,d"] = "堂夫侄女"
            correspondingAppellation["h,f,ob,d"] = "堂大姑姐/堂小姑妹"
            correspondingAppellation["h,f,ob,d,h"] = "堂大姑姐夫/堂小姑妹夫"
            correspondingAppellation["h,f,lb,d"] = "堂大姑姐/堂小姑妹"
            correspondingAppellation["h,f,lb,d,h"] = "堂大姑姐夫/堂小姑妹夫"
            correspondingAppellation["h,f,ob,d,s"] = "堂夫甥男"
            correspondingAppellation["h,f,ob,d,d"] = "堂夫甥女"
            correspondingAppellation["h,f,os"] = "姑婆"
            correspondingAppellation["h,f,os,h"] = "姑公"
            correspondingAppellation["h,f,os,s"] = "姑表大伯子/姑表小叔弟"
            correspondingAppellation["h,f,os,s,w"] = "姑表大伯嫂/姑表小叔弟妇"
            correspondingAppellation["h,f,ls,s"] = "姑表大伯子/姑表小叔弟"
            correspondingAppellation["h,f,ls,s,w"] = "姑表大伯嫂/姑表小叔弟妇"
            correspondingAppellation["h,f,os,s,s"] = "姑表夫侄男"
            correspondingAppellation["h,f,os,s,d"] = "姑表夫侄女"
            correspondingAppellation["h,f,os,d"] = "姑表大姑姐/姑表小姑妹"
            correspondingAppellation["h,f,os,d,h"] = "姑表大姑姐夫/姑表小姑妹夫"
            correspondingAppellation["h,f,ls,d"] = "姑表大姑姐/姑表小姑妹"
            correspondingAppellation["h,f,ls,d,h"] = "姑表大姑姐夫/姑表小姑妹夫"
            correspondingAppellation["h,f,os,d,s"] = "姑表夫甥男"
            correspondingAppellation["h,f,os,d,d"] = "姑表夫甥女"
            correspondingAppellation["h,f,lb,s,s"] = "堂夫侄男"
            correspondingAppellation["h,f,lb,s,d"] = "堂夫侄女"
            correspondingAppellation["h,f,lb,d,s"] = "堂夫甥男"
            correspondingAppellation["h,f,lb,d,d"] = "堂夫甥女"
            correspondingAppellation["h,f,ls"] = "姑婆"
            correspondingAppellation["h,f,ls,h"] = "姑公"
            correspondingAppellation["h,f,ls,s,s"] = "姑表夫侄男"
            correspondingAppellation["h,f,ls,s,d"] = "姑表夫侄女"
            correspondingAppellation["h,f,ls,d,s"] = "姑表夫甥男"
            correspondingAppellation["h,f,ls,d,d"] = "姑表夫甥女"
            correspondingAppellation["h,m"] = "婆婆"
            correspondingAppellation["h,m,ob"] = "舅公"
            correspondingAppellation["h,m,ob,w"] = "舅婆"
            correspondingAppellation["h,m,ob,s"] = "舅表大伯子/舅表小叔弟"
            correspondingAppellation["h,m,ob,s,w"] = "舅表大伯嫂/舅表小叔弟妇"
            correspondingAppellation["h,m,lb,s"] = "舅表大伯子/舅表小叔弟"
            correspondingAppellation["h,m,lb,s,w"] = "舅表大伯嫂/舅表小叔弟妇"
            correspondingAppellation["h,m,ob,s,s"] = "舅表夫侄男"
            correspondingAppellation["h,m,ob,s,d"] = "舅表夫侄女"
            correspondingAppellation["h,m,ob,d"] = "舅表大姑姐/舅表小姑妹"
            correspondingAppellation["h,m,ob,d,h"] = "舅表大姑姐夫/舅表小姑妹夫"
            correspondingAppellation["h,m,lb,d"] = "舅表大姑姐/舅表小姑妹"
            correspondingAppellation["h,m,lb,d,h"] = "舅表大姑姐夫/舅表小姑妹夫"
            correspondingAppellation["h,m,ob,d,s"] = "舅表夫甥男"
            correspondingAppellation["h,m,ob,d,d"] = "舅表夫甥女"
            correspondingAppellation["h,m,os"] = "姨婆"
            correspondingAppellation["h,m,os,h"] = "姨公"
            correspondingAppellation["h,m,os,s"] = "姨表大伯子/姨表小叔弟"
            correspondingAppellation["h,m,os,s,w"] = "姨表大伯嫂/姨表小叔弟妇"
            correspondingAppellation["h,m,ls,s"] = "姨表大伯子/姨表小叔弟"
            correspondingAppellation["h,m,ls,s,w"] = "姨表大伯嫂/姨表小叔弟妇"
            correspondingAppellation["h,m,os,s,s"] = "姨表夫侄男"
            correspondingAppellation["h,m,os,s,d"] = "姨表夫侄女"
            correspondingAppellation["h,m,os,d"] = "姨表大姑姐/姨表小姑妹"
            correspondingAppellation["h,m,os,d,h"] = "姨表大姑姐夫/姨表小姑妹夫"
            correspondingAppellation["h,m,ls,d"] = "姨表大姑姐/姨表小姑妹"
            correspondingAppellation["h,m,ls,d,h"] = "姨表大姑姐夫/姨表小姑妹夫"
            correspondingAppellation["h,m,os,d,s"] = "姨表夫甥男"
            correspondingAppellation["h,m,os,d,d"] = "姨表夫甥女"
            correspondingAppellation["h,m,lb"] = "舅公"
            correspondingAppellation["h,m,lb,w"] = "舅婆"
            correspondingAppellation["h,m,lb,s,s"] = "舅表夫侄男"
            correspondingAppellation["h,m,lb,s,d"] = "舅表夫侄女"
            correspondingAppellation["h,m,lb,d,s"] = "舅表夫甥男"
            correspondingAppellation["h,m,lb,d,d"] = "舅表夫甥女"
            correspondingAppellation["h,m,ls"] = "姨婆"
            correspondingAppellation["h,m,ls,h"] = "姨公"
            correspondingAppellation["h,m,ls,s,s"] = "姨表夫侄男"
            correspondingAppellation["h,m,ls,s,d"] = "姨表夫侄女"
            correspondingAppellation["h,m,ls,d,s"] = "姨表夫甥男"
            correspondingAppellation["h,m,ls,d,d"] = "姨表夫甥女"
            correspondingAppellation["h,ob"] = "大伯子"
            correspondingAppellation["h,ob,w"] = "大婶子"
            correspondingAppellation["h,lb"] = "小叔子"
            correspondingAppellation["h,lb,w"] = "小婶子"
            correspondingAppellation["h,ob,s"] = "叔侄"
            correspondingAppellation["h,lb,s"] = "叔侄"
            correspondingAppellation["h,os"] = "大姑子"
            correspondingAppellation["h,os,h"] = "大姑夫"
            correspondingAppellation["h,ls"] = "小姑子"
            correspondingAppellation["h,ls,h"] = "小姑夫"
            correspondingAppellation["h,os,s"] = "姑甥"
            correspondingAppellation["h,ls,s"] = "姑甥"
            correspondingAppellation["w"] = "老婆"
            correspondingAppellation["w,f"] = "岳父"
            correspondingAppellation["w,f,f"] = "太岳父"
            correspondingAppellation["w,f,f,ob"] = "太伯岳"
            correspondingAppellation["w,f,f,ob,w"] = "太伯岳母"
            correspondingAppellation["w,f,f,lb,"] = "太叔岳"
            correspondingAppellation["w,f,f,lb,w"] = "太叔岳母"
            correspondingAppellation["w,f,f,ob,s"] = "姻伯/姻叔"
            correspondingAppellation["w,f,f,ob,s,w"] = "姻姆/姻婶"
            correspondingAppellation["w,f,f,lb,s"] = "姻伯/姻叔"
            correspondingAppellation["w,f,f,lb,s,w"] = "姻姆/姻婶"
            correspondingAppellation["w,f,f,os"] = "太姑岳母"
            correspondingAppellation["w,f,f,os,h"] = "太姑岳父"
            correspondingAppellation["w,f,f,ls"] = "太姑岳母"
            correspondingAppellation["w,f,f,ls,h"] = "太姑岳父"
            correspondingAppellation["w,f,m"] = "太岳母"
            correspondingAppellation["w,f,m,ob"] = "太舅岳父"
            correspondingAppellation["w,f,m,ob,w"] = "太舅岳母"
            correspondingAppellation["w,f,m,os"] = "太姨岳母"
            correspondingAppellation["w,f,m,os,h"] = "太姨岳父"
            correspondingAppellation["w,f,ob,s"] = "堂大舅/堂舅仔"
            correspondingAppellation["w,f,ob,d"] = "堂大姨/堂姨仔"
            correspondingAppellation["w,f,lb,s"] = "堂大舅/堂舅仔"
            correspondingAppellation["w,f,lb,d"] = "堂大姨/堂姨仔"
            correspondingAppellation["w,f,m,lb"] = "太舅岳父"
            correspondingAppellation["w,f,m,lb,w"] = "太舅岳母"
            correspondingAppellation["w,f,m,ls"] = "太姨岳母"
            correspondingAppellation["w,f,m,ls,h"] = "太姨岳父"
            correspondingAppellation["w,f,ob"] = "伯岳"
            correspondingAppellation["w,f,ob,w"] = "伯岳母"
            correspondingAppellation["w,f,lb"] = "叔岳"
            correspondingAppellation["w,f,lb,w"] = "叔岳母"
            correspondingAppellation["w,f,os"] = "姑岳母"
            correspondingAppellation["w,f,os,h"] = "姑岳父"
            correspondingAppellation["w,f,os,s"] = "表大舅/表舅仔"
            correspondingAppellation["w,f,os,s,w"] = "表内嫂/表内弟妇"
            correspondingAppellation["w,f,ls,s"] = "表大舅/表舅仔"
            correspondingAppellation["w,f,ls,s,w"] = "表内嫂/表内弟妇"
            correspondingAppellation["w,f,os,d"] = "表大姨/表姨仔"
            correspondingAppellation["w,f,os,d,h"] = "表襟兄/表襟弟"
            correspondingAppellation["w,f,ls,d"] = "表大姨/表姨仔"
            correspondingAppellation["w,f,ls,d,h"] = "表襟兄/表襟弟"
            correspondingAppellation["w,f,ls"] = "姑岳母"
            correspondingAppellation["w,f,ls,h"] = "姑岳父"
            correspondingAppellation["w,m"] = "岳母"
            correspondingAppellation["w,m,f"] = "外太岳父"
            correspondingAppellation["w,m,m"] = "外太岳母"
            correspondingAppellation["w,m,ob"] = "舅岳父"
            correspondingAppellation["w,m,ob,w"] = "舅岳母"
            correspondingAppellation["w,m,ob,s"] = "表大舅/表舅仔"
            correspondingAppellation["w,m,ob,d"] = "表大姨/表姨仔"
            correspondingAppellation["w,m,lb,s"] = "表大舅/表舅仔"
            correspondingAppellation["w,m,lb,d"] = "表大姨/表姨仔"
            correspondingAppellation["w,m,os"] = "姨岳母"
            correspondingAppellation["w,m,os,h"] = "姨岳父"
            correspondingAppellation["w,m,os,s"] = "表大舅/表舅仔"
            correspondingAppellation["w,m,os,d"] = "表大姨/表姨仔"
            correspondingAppellation["w,m,ls,s"] = "表大舅/表舅仔"
            correspondingAppellation["w,m,ls,d"] = "表大姨/表姨仔"
            correspondingAppellation["w,ob,s"] = "内侄"
            correspondingAppellation["w,ob,s,w"] = "内侄媳妇"
            correspondingAppellation["w,ob,s,s"] = "内侄孙"
            correspondingAppellation["w,ob,s,s,w"] = "内侄孙媳妇"
            correspondingAppellation["w,ob,s,d"] = "内侄孙女"
            correspondingAppellation["w,ob,s,d,h"] = "内侄孙女婿"
            correspondingAppellation["w,ob,d"] = "内侄女"
            correspondingAppellation["w,ob,d,h"] = "内侄女婿"
            correspondingAppellation["w,ob,d,s"] = "外侄孙"
            correspondingAppellation["w,ob,d,s,w"] = "外侄孙媳妇"
            correspondingAppellation["w,ob,d,d"] = "外侄孙女"
            correspondingAppellation["w,ob,d,d,h"] = "外侄孙女婿"
            correspondingAppellation["w,m,lb"] = "舅岳父"
            correspondingAppellation["w,m,lb,w"] = "舅岳母"
            correspondingAppellation["w,m,ls"] = "姨岳母"
            correspondingAppellation["w,m,ls,h"] = "姨岳父"
            correspondingAppellation["w,lb,s"] = "内侄"
            correspondingAppellation["w,lb,s,w"] = "内侄媳妇"
            correspondingAppellation["w,lb,s,s"] = "内侄孙"
            correspondingAppellation["w,lb,s,s,w"] = "内侄孙媳妇"
            correspondingAppellation["w,lb,s,d"] = "内侄孙女"
            correspondingAppellation["w,lb,s,d,h"] = "内侄孙女婿"
            correspondingAppellation["w,lb,d"] = "内侄女"
            correspondingAppellation["w,lb,d,h"] = "内侄女婿"
            correspondingAppellation["w,lb,d,s"] = "外侄孙"
            correspondingAppellation["w,lb,d,s,w"] = "外侄孙媳妇"
            correspondingAppellation["w,lb,d,d"] = "外侄孙女"
            correspondingAppellation["w,lb,d,d,h"] = "外侄孙女婿"
            correspondingAppellation["w,ob"] = "大舅子"
            correspondingAppellation["w,ob,w"] = "舅嫂"
            correspondingAppellation["w,lb"] = "小舅子"
            correspondingAppellation["w,lb,w"] = "舅弟媳"
            correspondingAppellation["w,os,s"] = "内甥"
            correspondingAppellation["w,os,s,w"] = "姨甥媳妇"
            correspondingAppellation["w,os,s,s"] = "姨甥孙"
            correspondingAppellation["w,os,s,s,w"] = "姨甥孙媳妇"
            correspondingAppellation["w,os,s,d"] = "姨甥孙女"
            correspondingAppellation["w,os,s,d,h"] = "姨甥孙女婿"
            correspondingAppellation["w,os,d"] = "姨甥女"
            correspondingAppellation["w,os,d,h"] = "姨甥女婿"
            correspondingAppellation["w,os,d,s"] = "姨甥孙"
            correspondingAppellation["w,os,d,s,w"] = "姨甥孙媳妇"
            correspondingAppellation["w,os,d,d"] = "姨甥孙女"
            correspondingAppellation["w,os,d,d,h"] = "姨甥孙女婿"
            correspondingAppellation["w,ls,s"] = "内甥"
            correspondingAppellation["w,ls,s,w"] = "姨甥媳妇"
            correspondingAppellation["w,ls,s,s"] = "姨甥孙"
            correspondingAppellation["w,ls,s,s,w"] = "姨甥孙媳妇"
            correspondingAppellation["w,ls,s,d"] = "姨甥孙女"
            correspondingAppellation["w,ls,s,d,h"] = "姨甥孙女婿"
            correspondingAppellation["w,ls,d"] = "姨甥女"
            correspondingAppellation["w,ls,d,h"] = "姨甥女婿"
            correspondingAppellation["w,ls,d,s"] = "姨甥孙"
            correspondingAppellation["w,ls,d,s,w"] = "姨甥孙媳妇"
            correspondingAppellation["w,ls,d,d"] = "姨甥孙女"
            correspondingAppellation["w,ls,d,d,h"] = "姨甥孙女婿"
            correspondingAppellation["w,os"] = "大姨子"
            correspondingAppellation["w,os,h"] = "大姨夫"
            correspondingAppellation["w,ls"] = "小姨子"
            correspondingAppellation["w,ls,h"] = "小姨夫"
            correspondingAppellation["ob"] = "兄弟"
            correspondingAppellation["ob,w,f"] = "姻世伯"
            correspondingAppellation["ob,w,m"] = "姻伯母"
            correspondingAppellation["ob,w,ob"] = "姻兄/姻弟"
            correspondingAppellation["ob,w,lb"] = "姻兄/姻弟"
            correspondingAppellation["ob,s"] = "侄子"
            correspondingAppellation["ob,s,w"] = "侄媳"
            correspondingAppellation["ob,s,s"] = "侄孙"
            correspondingAppellation["ob,s,s,w"] = "侄孙媳"
            correspondingAppellation["ob,s,s,s"] = "侄曾孙"
            correspondingAppellation["ob,s,s,d"] = "侄曾孙女"
            correspondingAppellation["ob,s,d"] = "侄孙女"
            correspondingAppellation["ob,s,d,h"] = "侄孙女婿"
            correspondingAppellation["ob,d"] = "侄女"
            correspondingAppellation["ob,d,h"] = "侄女婿"
            correspondingAppellation["ob,d,s"] = "外侄孙"
            correspondingAppellation["ob,d,s,w"] = "外侄孙媳妇"
            correspondingAppellation["ob,d,d"] = "外侄孙女"
            correspondingAppellation["ob,d,d,h"] = "外侄孙女婿"
            correspondingAppellation["lb"] = "兄弟"
            correspondingAppellation["lb,w,f"] = "姻世伯"
            correspondingAppellation["lb,w,m"] = "姻伯母"
            correspondingAppellation["lb,w,ob"] = "姻兄/姻弟"
            correspondingAppellation["lb,w,lb"] = "姻兄/姻弟"
            correspondingAppellation["lb,s"] = "侄子"
            correspondingAppellation["lb,s,w"] = "侄媳"
            correspondingAppellation["lb,s,s"] = "侄孙"
            correspondingAppellation["lb,s,s,w"] = "侄孙媳"
            correspondingAppellation["lb,s,s,s"] = "侄曾孙"
            correspondingAppellation["lb,s,s,d"] = "侄曾孙女"
            correspondingAppellation["lb,s,d"] = "侄孙女"
            correspondingAppellation["lb,s,d,h"] = "侄孙女婿"
            correspondingAppellation["lb,d"] = "侄女"
            correspondingAppellation["lb,d,h"] = "侄女婿"
            correspondingAppellation["lb,d,s"] = "外侄孙"
            correspondingAppellation["lb,d,s,w"] = "外侄孙媳妇"
            correspondingAppellation["lb,d,d"] = "外侄孙女"
            correspondingAppellation["lb,d,d,h"] = "外侄孙女婿"
            correspondingAppellation["ob"] = "哥哥"
            correspondingAppellation["ob,w"] = "嫂子"
            correspondingAppellation["ob,w,f"] = "姻伯父"
            correspondingAppellation["ob,w,m"] = "姻伯母"
            correspondingAppellation["lb"] = "弟弟"
            correspondingAppellation["lb,w"] = "弟妹"
            correspondingAppellation["lb,w,f"] = "姻叔父"
            correspondingAppellation["lb,w,m"] = "姻叔母"
            correspondingAppellation["os"] = "姐妹"
            correspondingAppellation["os,h,f"] = "姻世伯"
            correspondingAppellation["os,h,m"] = "姻伯母"
            correspondingAppellation["os,h,ob"] = "姻兄/姻弟"
            correspondingAppellation["os,h,lb"] = "姻兄/姻弟"
            correspondingAppellation["os,s"] = "外甥"
            correspondingAppellation["os,s,w"] = "外甥媳妇"
            correspondingAppellation["os,s,s"] = "外甥孙"
            correspondingAppellation["os,s,s,w"] = "外甥孙媳妇"
            correspondingAppellation["os,s,s,s"] = "外曾甥孙"
            correspondingAppellation["os,s,s,d"] = "外曾甥孙女"
            correspondingAppellation["os,s,d"] = "外甥孙女"
            correspondingAppellation["os,s,d,h"] = "外甥孙女婿"
            correspondingAppellation["os,s,d,s"] = "外曾甥孙"
            correspondingAppellation["os,s,d,d"] = "外曾甥孙女"
            correspondingAppellation["os,d"] = "外甥女"
            correspondingAppellation["os,d,h"] = "外甥女婿"
            correspondingAppellation["os,d,s"] = "外甥孙"
            correspondingAppellation["os,d,s,w"] = "外甥孙媳妇"
            correspondingAppellation["os,d,s,s"] = "外曾甥孙"
            correspondingAppellation["os,d,s,d"] = "外曾甥孙女"
            correspondingAppellation["os,d,d"] = "外甥孙女"
            correspondingAppellation["os,d,d,h"] = "外甥孙女婿"
            correspondingAppellation["os,d,d,s"] = "外曾甥孙"
            correspondingAppellation["os,d,d,d"] = "外曾甥孙女"
            correspondingAppellation["ls"] = "姐妹"
            correspondingAppellation["ls,h,f"] = "姻世伯"
            correspondingAppellation["ls,h,m"] = "姻伯母"
            correspondingAppellation["ls,h,ob"] = "姻兄/姻弟"
            correspondingAppellation["ls,h,lb"] = "姻兄/姻弟"
            correspondingAppellation["ls,s"] = "外甥"
            correspondingAppellation["ls,s,w"] = "外甥媳妇"
            correspondingAppellation["ls,s,s"] = "外甥孙"
            correspondingAppellation["ls,s,s,w"] = "外甥孙媳妇"
            correspondingAppellation["ls,s,s,s"] = "外曾甥孙"
            correspondingAppellation["ls,s,s,d"] = "外曾甥孙女"
            correspondingAppellation["ls,s,d"] = "外甥孙女"
            correspondingAppellation["ls,s,d,h"] = "外甥孙女婿"
            correspondingAppellation["ls,s,d,s"] = "外曾甥孙"
            correspondingAppellation["ls,s,d,d"] = "外曾甥孙女"
            correspondingAppellation["ls,d"] = "外甥女"
            correspondingAppellation["ls,d,h"] = "外甥女婿"
            correspondingAppellation["ls,d,s"] = "外甥孙"
            correspondingAppellation["ls,d,s,w"] = "外甥孙媳妇"
            correspondingAppellation["ls,d,s,s"] = "外曾甥孙"
            correspondingAppellation["ls,d,s,d"] = "外曾甥孙女"
            correspondingAppellation["ls,d,d"] = "外甥孙女"
            correspondingAppellation["ls,d,d,h"] = "外甥孙女婿"
            correspondingAppellation["ls,d,d,s"] = "外曾甥孙"
            correspondingAppellation["ls,d,d,d"] = "外曾甥孙女"
            correspondingAppellation["os"] = "姐姐"
            correspondingAppellation["os,h"] = "姐夫"
            correspondingAppellation["ls"] = "妹妹"
            correspondingAppellation["ls,h"] = "妹夫"
            correspondingAppellation["s"] = "儿子"
            correspondingAppellation["s,w"] = "儿媳妇"
            correspondingAppellation["s,w,ob"] = "姻侄"
            correspondingAppellation["s,w,ob,s"] = "姻侄孙"
            correspondingAppellation["s,w,ob,d"] = "姻侄孙女"
            correspondingAppellation["s,w,os"] = "姻侄女"
            correspondingAppellation["s,w,os,s"] = "姻侄孙"
            correspondingAppellation["s,w,os,d"] = "姻侄孙女"
            correspondingAppellation["s,w,lb"] = "姻侄"
            correspondingAppellation["s,w,lb,s"] = "姻侄孙"
            correspondingAppellation["s,w,lb,d"] = "姻侄孙女"
            correspondingAppellation["s,w,ls"] = "姻侄女"
            correspondingAppellation["s,w,ls,s"] = "姻侄孙"
            correspondingAppellation["s,w,ls,d"] = "姻侄孙女"
            correspondingAppellation["s,s"] = "孙子"
            correspondingAppellation["s,s,w"] = "孙媳妇"
            correspondingAppellation["s,s,s"] = "曾孙"
            correspondingAppellation["s,s,s,w"] = "曾孙媳妇"
            correspondingAppellation["s,s,s,s"] = "玄孙"
            correspondingAppellation["s,s,s,d"] = "玄孙女"
            correspondingAppellation["s,s,s,s,s"] = "来孙"
            correspondingAppellation["s,s,s,s,d"] = "来孙女"
            correspondingAppellation["s,s,s,s,s,s"] = "晜孙"
            correspondingAppellation["s,s,s,s,s,d"] = "晜孙女"
            correspondingAppellation["s,s,s,s,s,s,s"] = "仍孙"
            correspondingAppellation["s,s,s,s,s,s,d"] = "仍孙女"
            correspondingAppellation["s,s,d"] = "曾孙女"
            correspondingAppellation["s,s,d,h"] = "曾孙女婿"
            correspondingAppellation["s,s,d,s"] = "外玄孙"
            correspondingAppellation["s,s,d,d"] = "外玄孙女"
            correspondingAppellation["s,d"] = "孙女"
            correspondingAppellation["s,d,h"] = "孙女婿"
            correspondingAppellation["s,d,s"] = "曾外孙"
            correspondingAppellation["s,d,d"] = "曾外孙女"
            correspondingAppellation["d"] = "女儿"
            correspondingAppellation["d,h"] = "女婿"
            correspondingAppellation["d,h,ob"] = "姻侄"
            correspondingAppellation["d,h,ob,s"] = "姻侄孙"
            correspondingAppellation["d,h,ob,d"] = "姻侄孙女"
            correspondingAppellation["d,h,os"] = "姻侄女"
            correspondingAppellation["d,h,os,s"] = "姻侄孙"
            correspondingAppellation["d,h,os,d"] = "姻侄孙女"
            correspondingAppellation["d,h,lb"] = "姻侄"
            correspondingAppellation["d,h,lb,s"] = "姻侄孙"
            correspondingAppellation["d,h,lb,d"] = "姻侄孙女"
            correspondingAppellation["d,h,ls"] = "姻侄女"
            correspondingAppellation["d,h,ls,s"] = "姻侄孙"
            correspondingAppellation["d,h,ls,d"] = "姻侄孙女"
            correspondingAppellation["d,s"] = "外孙"
            correspondingAppellation["d,s,w"] = "外孙媳"
            correspondingAppellation["d,s,s"] = "外曾孙"
            correspondingAppellation["d,s,d"] = "外曾孙女"
            correspondingAppellation["d,d"] = "外孙女"
            correspondingAppellation["d,d,h"] = "外孙女婿"
            correspondingAppellation["d,d,s"] = "外曾外孙"
            correspondingAppellation["d,d,d"] = "外曾外孙女"
            correspondingAppellation["s,w,m"] = "亲家母"
            correspondingAppellation["s,w,f"] = "亲家公"
            correspondingAppellation["s,w,f,f"] = "太姻翁"
            correspondingAppellation["s,w,f,m"] = "太姻姆"
            correspondingAppellation["s,w,f,ob"] = "姻兄"
            correspondingAppellation["s,w,f,lb"] = "姻弟"
            correspondingAppellation["d,h,m"] = "亲家母"
            correspondingAppellation["d,h,f"] = "亲家公"
            correspondingAppellation["d,h,f,f"] = "太姻翁"
            correspondingAppellation["d,h,f,m"] = "太姻姆"
            correspondingAppellation["d,h,f,ob"] = "姻兄"
            correspondingAppellation["d,h,f,lb"] = "姻弟"

            /*----------------------------亲戚互称------------------------------*/
            eachAppellation[""] = ""     //自己-自己
            eachAppellation["h"] = "w"   //老公-老婆
            eachAppellation["w"] = "h"   //老婆-老公
            eachAppellation["fM"] = "s"  //爸爸（后代男孩）-儿子
            eachAppellation["fF"] = "d"  //爸爸（后代女孩）-女儿
            eachAppellation["mM"] = "s"  //妈妈（后代男孩）-儿子
            eachAppellation["mF"] = "d"  //妈妈（后代女孩）-女儿
            eachAppellation["obM"] = "lb" //哥哥（同辈男性）-弟弟
            eachAppellation["obF"] = "ls" //哥哥（同辈女性）-妹妹
            eachAppellation["lbM"] = "ob" //弟弟（同辈男性）-哥哥
            eachAppellation["lbF"] = "os" //弟弟（同辈女性）-姐姐
            eachAppellation["osM"] = "lb" //姐姐（同辈男性）-弟弟
            eachAppellation["osF"] = "ls" //姐姐（同辈女性）-妹妹
            eachAppellation["lsM"] = "ob" //妹妹（同辈男性）-哥哥
            eachAppellation["lsF"] = "os" //妹妹（同辈女性）-姐姐
            eachAppellation["sM"] = "f"  //儿子（长辈男性）-爸爸
            eachAppellation["sF"] = "m"  //儿子（长辈女性）-妈妈
            eachAppellation["dM"] = "f"  //女儿（长辈男性）-爸爸
            eachAppellation["dF"] = "m"  //女儿（长辈女性）-妈妈

        }
    }

    fun initData() {
        currentRelative.delete(0, currentRelative.length)
        currentRelative.append("我")
    }

    // 查找亲戚称谓
    fun searchRelative(): String {
        val results = SqList(20)
        var relativeResults = ""
        for (i in 1 until tempCurrentRelative.length()) {
            if (correspondingAppellation[tempCurrentRelative.getItem(i)] != null) {
                results.add(correspondingAppellation[tempCurrentRelative.getItem(i)])
            }
        }
        for (i in 2 until results.length() - 1) {
            relativeResults = (relativeResults + results.getItem(i)) + "/"
        }
        relativeResults += results.getItem(results.length() - 1)
        return relativeResults
    }


    // 判断亲戚性别
    fun isMale(): Boolean {
        // 倒数第三个字符串sex
        return when (sex) {
            "h", "f", "ob", "lb", "s" -> {
                //丈夫、爸爸、哥哥、弟弟、儿子-男性
                true
            }

            "w", "m", "os", "ls", "d" -> {
                //妻子、妈妈、姐姐、妹妹、女儿-女性
                false
            }

            else -> false
        }
    }

    // 化简称谓关系链
    fun simplyRelative() {
        for (i in tempCurrentRelative.length() - 1 downTo 1)  //循环结束控制i>0:i=0存放用户原始输入亲戚关系
        {
            val pattern = "((\\w{1,3},)*)(\\w{1,3},\\w{1,3})" //用户当前输入且化简后的亲戚关系的匹配模式：(…x，)(x，x)
            val r = Pattern.compile(pattern)
            val m = r.matcher(tempCurrentRelative.getItem(i))
            if (m.find()) {
                when (m.group(3)) {
                    "m,h", "os,f", "ob,f", "ls,f", "lb,f" -> {
                        // 妈妈的老公、兄弟姐妹的爸爸-爸爸
                        tempCurrentRelative.changeValue(i, m.group(1) + "f")
                    }

                    "f,w", "os,m", "ob,m", "ls,m", "lb,m" -> {
                        // 爸爸的老婆、兄弟姐妹的妈妈-妈妈
                        tempCurrentRelative.changeValue(i, m.group(1) + "m")
                    }

                    "d,ob", "d,lb", "s,ob", "s,lb" -> {
                        // 孩子的兄弟是自己的儿子
                        tempCurrentRelative.changeValue(i, m.group(1) + "s")
                    }

                    "d,os", "d,ls", "s,os", "s,ls" -> {
                        // 孩子的姐妹是自己的女儿
                        tempCurrentRelative.changeValue(i, m.group(1) + "d")
                    }

                    "os,ob", "ob,ob" -> {
                        // 哥哥
                        tempCurrentRelative.changeValue(i, m.group(1) + "ob")
                    }

                    "ls,lb", "lb,lb" -> {
                        // 弟弟
                        tempCurrentRelative.changeValue(i, m.group(1) + "lb")
                    }

                    "f,s", "m,s", "os,lb", "ob,lb", "ls,ob", "lb,ob" -> {
                        // 可能是哥哥，弟弟，自己
                        tempCurrentRelative.changeValue(i, m.group(1) + "ob")
                        tempCurrentRelative.add(m.group(1) + "lb")
                        if (m.group(1) == "") { //如果用户仅输入了两位亲戚，则添加自己
                            tempCurrentRelative.add("")
                        } else { //获取倒数第三位性别，男性有可能是自己可化简为“”，女性只可能是哥哥或弟弟，无需化简为“”
                            sex = m.group(1).substring(0, m.group(1).length - 1)
                            if (sex.indexOf(',') != -1) {
                                sex = sex.substring(sex.lastIndexOf(',') + 1, sex.length)
                            }
                            if (isMale()) {
                                tempCurrentRelative.add(
                                    m.group(1).substring(0, m.group(1).lastIndexOf(','))
                                )
                            }
                        }
                    }

                    "os,os", "ob,os" -> {
                        // 姐姐
                        tempCurrentRelative.changeValue(i, m.group(1) + "os")
                    }

                    "ls,ls", "lb,ls" -> {
                        // 妹妹
                        tempCurrentRelative.changeValue(i, m.group(1) + "ls")
                    }

                    "f,d", "m,d", "ob,ls", "os,ls", "lb,os", "ls,os" -> {
                        // 可能是姐姐，妹妹，自己
                        tempCurrentRelative.changeValue(i, m.group(1) + "os")
                        tempCurrentRelative.add(m.group(1) + "ls")
                        if (m.group(1) == "") { //如果用户仅输入了两位亲戚，则添加自己
                            tempCurrentRelative.add("")
                        } else { //获取倒数第三位性别，女性有可能是自己可化简为“”，男性只可能是哥哥或弟弟，无需化简为“”
                            sex = m.group(1).substring(0, m.group(1).length - 1)
                            if (sex.indexOf(',') != -1) {
                                sex = sex.substring(sex.lastIndexOf(',') + 1, sex.length)
                            }
                            if (!isMale()) {
                                tempCurrentRelative.add(
                                    m.group(1).substring(0, m.group(1).lastIndexOf(','))
                                )
                            }
                        }
                    }

                    "d,f", "s,f" -> {
                        // 女儿或儿子的爸爸，需判断倒数第三位性别：男性-爸爸，女性-妈妈的老公（+“h”）
                        // 例：妹妹的女儿的爸爸-妹妹的老公；弟弟的女儿的爸爸-弟弟
                        if (m.group(1).isNotEmpty()) {
                            sex = m.group(1).substring(0, m.group(1).length - 1)
                            if (sex.indexOf(',') != -1) {
                                sex = sex.substring(sex.lastIndexOf(',') + 1, sex.length)
                            }
                            if (isMale()) {
                                tempCurrentRelative.changeValue(
                                    i,
                                    m.group(1).substring(0, m.group(1).lastIndexOf(','))
                                )
                            } else {
                                tempCurrentRelative.changeValue(i, m.group(1) + "h")
                            }
                            simplyRelative()
                        } else { //如果用户仅输入两位亲戚，则可能是老公或自己
                            tempCurrentRelative.changeValue(i, "h")
                            tempCurrentRelative.add("")
                        }
                    }

                    "d,m", "s,m" -> {
                        // 女儿或儿子的妈妈，需判断倒数第三位性别：女性-妈妈，男性-爸爸的老婆
                        // 例：妹妹的女儿的妈妈-妹妹；弟弟的女儿的妈妈-弟弟的妻子
                        if (m.group(1).isNotEmpty()) {
                            sex = m.group(1).substring(0, m.group(1).length - 1)
                            if (sex.indexOf(',') != -1) {
                                sex = sex.substring(sex.lastIndexOf(',') + 1, sex.length)
                            }
                            if (isMale()) {
                                tempCurrentRelative.changeValue(i, m.group(1) + "w")
                            } else {
                                tempCurrentRelative.changeValue(
                                    i,
                                    m.group(1).substring(0, m.group(1).lastIndexOf(','))
                                )
                            }

                            simplyRelative()
                        } else { //如果用户仅输入两位亲戚，则可能是老婆或自己
                            tempCurrentRelative.changeValue(i, "w")
                            tempCurrentRelative.add("")
                        }
                    }

                    "h,s", "w,s" -> {
                        // 夫妻的儿子是自己的儿子
                        tempCurrentRelative.changeValue(i, m.group(1) + "s")
                    }

                    "h,d", "w,d" -> {
                        // 夫妻的女儿是自己的女儿
                        tempCurrentRelative.changeValue(i, m.group(1) + "d")
                    }

                    "w,h", "h,w" -> {
                        // 老公的老婆
                        tempCurrentRelative.changeValue(i, m.group(1) + "")
                        if (tempCurrentRelative.getItem(i).length !== 0) {
                            tempCurrentRelative.changeValue(
                                i, tempCurrentRelative.getItem(i).substring(
                                    0,
                                    tempCurrentRelative.getItem(i).length - 1
                                )
                            )
                        }
                    }

                    else -> {}
                }
            }
        }
    }
}